# Webcam
CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

# MediaPipe Hand Detection
MAX_HANDS = 1
DETECTION_CONFIDENCE = 0.8
TRACKING_CONFIDENCE = 0.8

# Gesture Sensitivity
SMOOTHING_FACTOR = 5
GESTURE_HOLD_FRAMES = 8 

# Volume
VOLUME_MIN = 0
VOLUME_MAX = 100

# Brightness
BRIGHTNESS_MIN = 10
BRIGHTNESS_MAX = 100

# Overlay UI
FONT = 0x00 
FONT_SCALE = 0.8
FONT_THICKNESS = 2
UI_COLOR = (0, 255, 0)        # green
WARNING_COLOR = (0, 0, 255)   # red